version: '1.4'

services:
  db:
    image: postgres:15-alpine
    restart: always
    container_name: postgres
    env_file:
      - ./envs/postgres.env
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      - postgres_data:/data/postgres

  backend:
    # todo: создать скрипт для миграции
    build: ../backend
    container_name: main_backend
    command: sh entrypoint.sh
    ports:
      - "8000:8000"
    env_file: ./envs/backend.env
    depends_on:
      - db
  admin:
    build: ../admin
    container_name: admin_pannel
    command: sh entrypoint.sh
    ports:
      - "8001:8001"
    env_file: ./envs/admin.env
    volumes:
      - ./app/:/usr/src/app/
    depends_on:
      - db
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ../nginx/api_gateway.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - admin


volumes:
  postgres_data:
    driver: local
