"""right_answer

Revision ID: 156fbb167963
Revises: 408b865e914a
Create Date: 2023-11-27 17:44:50.964711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156fbb167963'
down_revision = '408b865e914a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_right_answer', table_name='task')
    op.drop_column('task', 'right_answer')
    op.add_column('task_answer', sa.Column('is_right', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_answer', 'is_right')
    op.add_column('task', sa.Column('right_answer', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_task_right_answer', 'task', ['right_answer'], unique=False)
    # ### end Alembic commands ###
